# Generated by Django 4.1.1 on 2024-02-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
