# Generated by Django 4.1.1 on 2024-03-02 17:28

import MainApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments_images/', validators=[MainApp.validators.validate_image_extension, MainApp.validators.validate_image_size]),
        ),
    ]
